spring:
  datasource:
    url: jdbc:mysql://10.170.230.102:3306/jd_wutong_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: qytest_rw
    password: qytest_passwd
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

graceful-response:
  responseStyle: 1
  defaultSuccessCode: 200
  defaultErrorCode: 500
