spring:
  profiles:
    active: h2

server:
  port: 8080

graceful-response:
  responseStyle: 1
  defaultSuccessCode: 200
  defaultErrorCode: 500

audit:
  log:
    enabled: true
    basePackages: com.taoyuanx.common.log.web
    logScene: high
    appId: default


db:
  init:
    enabled: true



